const commandDocumentationPart3 = {
  'cage': 'Economy: Opens a mysterious cage for rewards.',
  'giveaway': 'General: Shows status of active giveaways.',
  'giveawayinfo': 'Utility: Details about the current giveaway.',
  'startgiveaway': 'Admin: Starts a new community giveaway.',
  'endgiveaway': 'Admin: Manually ends a giveaway and picks winners.',
  'autogiveaway': 'Admin: Configures the automated giveaway system.',
  'lottery': 'Economy: Participate in or view lottery info.',
  'lotteryinfo': 'Utility: Current pool and ticket information.',
  'startlottery': 'Admin: Starts a new lottery for the server.',
  'stoplottery': 'Admin: Stops the active lottery.',
  'endlottery': 'Admin: Ends the lottery and distributes prizes.',
  'autolottery': 'Admin: Configures the automated lottery system.',
  'work': 'Economy: Perform your assigned job for currency.',
  'miner': 'Job: Specific actions for the Miner role.',
  'caretaker': 'Job: Specific actions for the Caretaker role.',
  'farmer': 'Job: Specific actions for the Farmer role.',
  'zookeeper': 'Job: Specific actions for the Zookeeper role.',
  'ranger': 'Job: Specific actions for the Ranger role.',
  'crafttool': 'Economy: Craft better tools for work efficiency.',
  'upgrade': 'Economy: General command for house/tool upgrades.',
  'upgradehouse': 'Economy: Upgrades your house for better job rewards.',
  'inventory': 'User: Lists your current items and resources.',
  'inv': 'Shortcut: Alias for inventory.',
  'market': 'Economy: Access the player-to-player marketplace.',
  'auction': 'Economy: Access the character auction system.',
  'clearmarket': 'Admin: Clears all listings from the market.',
  'clearauctions': 'Admin: Clears all active auctions.',
  'endauction': 'Admin: Forcefully ends a specific auction.',
  'giveores': 'Admin: Grants ores to a user.',
  'giveore': 'Admin: Alias for granting ore.',
  'givewood': 'Admin: Grants wood resources to a user.',
  'givetool': 'Admin: Grants a specific tool to a user.',
  'viewmarket': 'Utility: Shows current marketplace listings.',
  'viewauctions': 'Utility: Shows current active auctions.',
  'createchar': 'Admin: Directly creates a new character.',
  'addchar': 'Admin: Alias for creating a character.',
  'createchar2': 'Admin: Experimental version of character creator.',
  'editchar': 'Admin: Modifies stats/info of an existing character.',
  'removechar': 'Admin: Deletes a character from the system.',
  'listchars': 'Utility: Lists all characters in the bot database.',
  'setability': 'Admin: Sets the passive ability for a character.',
  'setmove': 'Admin: Configures a battle move for a character.',
  'effecttypes': 'Utility: Lists all possible status effects for moves.',
  'games': 'Utility: Lists available game modes/bundles.',
  'bundles': 'Utility: Alias for viewing game bundles.',
  'creategame': 'Admin: Creates a new game instance.',
  'createbundle': 'Admin: Creates a new collection bundle.',
  'deletegame': 'Admin: Deletes a game instance.',
  'deletebundle': 'Admin: Deletes a collection bundle.',
  'setgame': 'Admin: Sets the active game for the server.',
  'selectgame': 'Admin: Alias for setting the game.',
  'gameinfo': 'Utility: Displays details about a game mode.',
  'bundleinfo': 'Utility: Displays details about a bundle.',
  'bundlechars': 'Utility: Lists characters within a bundle.',
  'gamechars': 'Utility: Lists characters assigned to a game.',
  'assigngame': 'Admin: Assigns a character to a specific game.',
  'assignbundle': 'Admin: Assigns a character to a bundle.',
  'bulkassign': 'Admin: Assigns multiple characters at once.',
  'importchars': 'Admin: Imports character data from external source.',
  'backfillgames': 'Admin: Auto-assigns characters to default games.',
  'abilityeffects': 'Utility: Lists details of all character abilities.',
  'submit': 'User: Submits a character for bot approval.',
  'submitchar': 'User: Alias for submitting a character.',
  'mysubmissions': 'User: View your character submission history.',
  'submissions': 'Admin: View characters awaiting review.',
  'pendingsubs': 'Admin: Alias for character submissions.',
  'reviewsub': 'Admin: Detailed view of a specific submission.',
  'approve': 'Admin: Approves a character submission.',
  'approvechar': 'Admin: Alias for approving a character.',
  'reject': 'Admin: Rejects a character submission.',
  'rejectchar': 'Admin: Alias for rejecting a character.',
  'cancelsub': 'User: Cancels your own pending submission.',
  'serverstatus': 'Utility: Shows health and status of the server.',
  'setupstatus': 'Admin: Shows how much of setup is completed.',
  'togglegame': 'Admin: Enables/disables a specific game mode.',
  'gamestats': 'Utility: Shows global statistics for a game.',
  'warn': 'Moderation: Warns a user and logs the infraction.',
  'warnings': 'Moderation: Shows warning history for a user.',
  'clearwarnings': 'Moderation: Removes all warnings from a user.',
  'botban': 'Moderation: Bans a user from using any bot commands.',
  'unbotban': 'Moderation: Unbans a user from the bot.',
  'botunban': 'Moderation: Alias for unbanning from the bot.',
  'mute': 'Moderation: Mutes a user in the current server.',
  'unmute': 'Moderation: Unmutes a user in the server.',
  'clear': 'Moderation: Deletes messages in the current channel.',
  'purge': 'Moderation: Alias for clearing messages.',
  'announce': 'Admin: Sends an announcement message to the server.',
  'modlogs': 'Moderation: Shows the server\'s moderation history.',
  'modstats': 'Moderation: Shows stats for the moderation team.',
  'flags': 'Moderation: View system flags on a user.',
  'userflags': 'Moderation: Alias for viewing user flags.',
  'clearflags': 'Moderation: Removes system flags from a user.',
  'suspicious': 'Moderation: Lists users flagged for suspicious activity.',
  'transactions': 'Admin: View recent economy transactions for a user.',
  'anticheatstats': 'Admin: Shows performance of the anti-cheat system.',
  'acstats': 'Shortcut: Alias for anti-cheat stats.',
  'modhelp': 'Moderation: Shows help for moderation commands.'
};

module.exports = { commandDocumentationPart3 };