const commandDocumentationPart2 = {
  'showwork': 'Admin: Displays the current work-related configuration.',
  'assignwork': 'Admin: Manually assigns a work task to a user.',
  'equipskin': 'Character: Equips a collected skin to a character.',
  'setprofilepic': 'User: Sets your global profile picture.',
  'setpfp': 'User: Alias for setting your profile picture.',
  'b': 'Shortcut: Common shortcut for battle commands.',
  'battle': 'Game: Initiates a battle against a player or AI.',
  'ustshop': 'Economy: Browse items available for purchase with UST.',
  'skinshop': 'Economy: Browse and buy character skins.',
  'addcosmetic': 'Admin: Adds a new cosmetic item to the shop.',
  'removecosmetic': 'Admin: Removes a cosmetic item from the shop.',
  'updatecosmeticprice': 'Admin: Changes the price of a cosmetic item.',
  'i': 'Shortcut: Common shortcut for info or inventory commands.',
  'info': 'General: Displays help or specific system information.',
  'quests': 'General: View your current active and completed quests.',
  'quest': 'General: Alias for viewing quest information.',
  'claim': 'General: Claims rewards for completed tasks or quests.',
  'claimall': 'General: Claims all available rewards in one go.',
  'shards': 'Economy: Shows your current character shard balance.',
  'craft': 'Economy: Opens the crafting menu for items/boosters.',
  'boost': 'Economy: Applies a booster to your character or account.',
  'mail': 'Social: Check your mailbox for rewards and messages.',
  'mailbox': 'Social: Alias for checking your mail.',
  'claimmail': 'Social: Claims all attachments from your mailbox.',
  'clearmail': 'Social: Deletes all read or claimed messages.',
  'sendmail': 'Admin: Sends a message or gift to all bot users.',
  'news': 'General: Shows latest bot updates and announcements.',
  'postnews': 'SuperAdmin: Publishes a new entry to the news system.',
  'leaderboard': 'Social: Displays competitive rankings.',
  'lb': 'Social: Alias for the leaderboard command.',
  'daily': 'Economy: Claims your daily reward and updates streak.',
  'season': 'General: View current season progress and pass.',
  'seasonpass': 'General: Alias for viewing the season pass.',
  'sp': 'Shortcut: Alias for season pass.',
  'seasontasks': 'General: View tasks specific to the current season.',
  'stasks': 'Shortcut: Alias for season tasks.',
  'dailytasks': 'General: View your assigned daily season tasks.',
  'dt': 'Shortcut: Alias for daily tasks.',
  'seasonrewards': 'General: View rewards available in the season pass.',
  'srewards': 'Shortcut: Alias for season rewards.',
  'taskclaimall': 'General: Claims all finished season task rewards.',
  'tclaim': 'Shortcut: Alias for claiming all tasks.',
  'seasonclaimall': 'General: Claims all reached season pass milestones.',
  'sclaim': 'Shortcut: Alias for claiming all season rewards.',
  'globalboard': 'Social: View global rankings across all servers.',
  'gboard': 'Shortcut: Alias for global leaderboard.',
  'globalleaderboard': 'Social: Full name for global rankings.',
  'glb': 'Shortcut: Alias for global leaderboard.',
  'challenges': 'General: View active weekly or special challenges.',
  'challenge': 'General: Alias for viewing challenges.',
  'weekly': 'General: View the current set of weekly challenges.',
  'weeklychallenges': 'General: Alias for weekly challenges.',
  'claimchallenge': 'General: Claims reward for a specific challenge.',
  'claimchal': 'Shortcut: Alias for claiming a challenge.',
  'achievements': 'User: View your unlocked badges and achievements.',
  'badges': 'User: Alias for viewing achievements.',
  'achieve': 'User: Alias for viewing achievements.',
  'serverstats': 'Admin: Shows usage and growth stats for the server.',
  'stats': 'User: Displays your personal game statistics.',
  'analytics': 'Admin: Alias for viewing server statistics.',
  'coinduel': 'Game: Bet coins in a duel against another player.',
  'coinflip': 'Game: Flip a coin to bet and win currency.',
  'diceclash': 'Game: Roll dice against the bot or a player.',
  'dice': 'Game: Alias for the dice command.',
  'dooroffate': 'Game: Choose a door and face a random outcome.',
  'door': 'Game: Alias for Door of Fate.',
  'almostwin': 'Game: Play a game of chance with high rewards.',
  'slot': 'Game: Play the slot machine for various prizes.',
  'roll': 'Game: Alias for rolling dice or slots.',
  'rps': 'Game: Play Rock-Paper-Scissors.',
  'rockpaperscissors': 'Game: Full name for Rock-Paper-Scissors.',
  'event': 'General: View info about the current active event.',
  'setbattle': 'Admin: Configures battle parameters for the server.',
  'settrophies': 'Admin: Sets or resets trophy counts for users.',
  'adminaddpfp': 'Admin: Forcefully adds a pfp to a user.',
  'adminremovepfp': 'Admin: Forcefully removes a pfp from a user.',
  'addtrivia': 'Admin: Adds a question to the trivia pool.',
  'removetrivia': 'Admin: Removes a question from the trivia pool.',
  'listtrivia': 'Admin: Lists all questions in the trivia pool.',
  'setevent': 'Admin: Configures server-specific event settings.',
  'startevent': 'Admin: Manually begins a scheduled or custom event.',
  'stopevent': 'Admin: Ends the current active event.',
  'eventschedule': 'Utility: Shows the calendar of upcoming events.',
  'servers': 'SuperAdmin: Lists all servers using the bot.',
  'serverlist': 'SuperAdmin: Alias for listing servers.',
  'removeserver': 'SuperAdmin: Remotely removes the bot from a server.',
  'leaveserver': 'SuperAdmin: Alias for leaving a server.',
  'deleteserver': 'SuperAdmin: Wipes all data for a specific server.',
  'reset': 'Admin: Resets server configuration to defaults.',
  'botinfo': 'Utility: Displays technical bot information.',
  'ptsend': 'Admin: Manually triggers a personalized task for a user.',
  'pttoggle': 'Admin: Toggles the personalized task system.',
  'ptstats': 'Admin: Shows statistics for personalized tasks.',
  'ptcustom': 'Admin: Creates a custom personalized task.',
  'history': 'User: View your recent actions and transactions.',
  'pttasks': 'User: View your current personalized tasks.',
  'ptsendtask': 'Admin: Sends a specific task to a user.',
  'perms': 'Utility: Shows permissions for the current channel.',
  'hub': 'General: Opens the main interactive hub menu.',
  'menu': 'General: Alias for the hub menu.',
  'home': 'General: Alias for the hub menu.',
  'guide': 'Utility: Provides a link to the player guide.',
  'tutorial': 'Utility: Starts the onboarding tutorial.',
  'quickstart': 'Utility: Shows a quick guide for new players.',
  'discovery': 'General: Explore new features and systems.',
  'explore': 'General: Alias for discovery.',
  'talk': 'Utility: Start a conversation with the bot (if enabled).',
  'help': 'Utility: Displays the general help command.',
  'overview': 'Utility: Shows a summary of the bot\'s systems.',
  'systems': 'Utility: Lists all active bot modules.',
  'workguide': 'Utility: Guide on how to perform various jobs.',
  'workhelp': 'Utility: Alias for the work guide.',
  'keys': 'Economy: View your current character keys.',
  'unlock': 'Character: Unlock a character with keys.',
  'charkeys': 'Utility: List of characters unlockable via keys.',
  'characterkeys': 'Utility: Alias for character keys list.',
  'ck': 'Shortcut: Alias for character keys.',
  'keyunlock': 'Character: Specifically handles unlocking with keys.',
  'convertkeys': 'Economy: Converts excess keys into tokens.',
  'keyrush': 'Event: Check status of Key Rush event.',
  'keyrushstatus': 'Utility: Details about active Key Rush.',
  'grantkeyrush': 'Admin: Manually starts a Key Rush event.',
  'stoprush': 'Admin: Stops an active Key Rush event.',
  'collectibles': 'User: View your collected items and artifacts.',
  'collectibleitems': 'User: Alias for viewing collectibles.',
  'colitems': 'Shortcut: Alias for collectible items.',
  'mycollectibles': 'User: Alias for your collection.',
  'myitems': 'User: View your item inventory.',
  'mycolitems': 'Shortcut: Alias for your collectibles.',
  'setitem': 'User: Sets an item to be displayed on your profile.',
  'selectitem': 'User: Alias for setting a profile item.',
  'displayitem': 'User: Alias for showing an item.',
  'clearitem': 'User: Removes the displayed item from your profile.',
  'removeitem': 'User: Alias for clearing profile item.',
  'sellitem': 'Economy: Sells an item from your inventory.',
  'submititem': 'User: Submits an item for bot approval.',
  'itemsubmissions': 'Admin: Lists items awaiting review.',
  'pendingitems': 'Admin: Alias for item submissions.',
  'approveitem': 'Admin: Approves a submitted item.',
  'rejectitem': 'Admin: Rejects a submitted item.',
  'additem': 'Admin: Directly creates a new item in the system.',
  'createitem': 'Admin: Alias for adding an item.',
  'deleteitem': 'Admin: Deletes an item from the global system.',
  'delitem': 'Shortcut: Alias for deleting an item.',
  'toggleitemtrait': 'Admin: Toggles properties like "droppable" on items.',
  'setitemglobal': 'Admin: Sets whether an item is available globally.',
  'setitemprobability': 'Admin: Configures the drop chance for an item.',
  'setitemprob': 'Shortcut: Alias for setting probability.',
  'setitemavailability': 'Admin: Sets if an item is currently obtainable.',
  'setitemtime': 'Admin: Alias for setting availability.',
  'giveitem': 'Admin: Gives a specific item to a user.',
  'takeitem': 'Admin: Removes an item from a user\'s inventory.',
  'recalcitems': 'Admin: Recalculates market values for all items.',
  'recalculateitems': 'Admin: Alias for recalculating items.'
};

module.exports = { commandDocumentationPart2 };