const commandDocumentationPart1 = {
  'core': 'Internal: System core configuration identifier.',
  'permissions': 'Internal: System permissions configuration identifier.',
  'channels': 'Internal: System channels configuration identifier.',
  'features': 'Internal: System features configuration identifier.',
  'notifications': 'Internal: System notifications configuration identifier.',
  'pingSettings': 'Internal: System ping settings configuration identifier.',
  'moderation': 'Internal: System moderation configuration identifier.',
  'economy': 'Internal: System economy configuration identifier.',
  'onboarding': 'Internal: System onboarding configuration identifier.',
  'automation': 'Internal: System automation configuration identifier.',
  'characterAdded': 'Event: Triggered when a character is added.',
  'characterRemoved': 'Event: Triggered when a character is removed.',
  'charactersUpdated': 'Event: Triggered when character details are updated.',
  'collectibleAdded': 'Event: Triggered when a collectible is added.',
  'collectibleRemoved': 'Event: Triggered when a collectible is removed.',
  'collectiblesUpdated': 'Event: Triggered when collectible details are updated.',
  'setupCompleted': 'Event: Triggered when server setup is finished.',
  'setup': 'Wizard: Guides server owners through initial bot configuration.',
  'setdropchannel': 'Admin: Configures the channel for character drops.',
  'seteventschannel': 'Admin: Configures the channel for server events.',
  'addadmin': 'Admin: Grants admin privileges to a specified user.',
  'removeadmin': 'Admin: Revokes admin privileges from a specified user.',
  'setlevelup': 'Admin: Configures level-up settings and notifications.',
  'levelupconfig': 'Admin: Views or modifies level-up system configuration.',
  'levelupmsg': 'Admin: Sets a custom message for level-up announcements.',
  'setleveluprole': 'Admin: Configures roles awarded upon reaching certain levels.',
  'setroleevents': 'Admin: Links specific roles to bot event notifications.',
  'toggletasks': 'Admin: Enables or disables the task system in the server.',
  'togglepersonalizedtasks': 'Admin: Toggles personalized task delivery for members.',
  'toggleeventpings': 'Admin: Enables or disables role pings for all events.',
  'toggleeventping': 'Admin: Toggles pings for a specific event type.',
  'admins': 'Utility: Lists all administrators for the current server.',
  'botadmins': 'Utility: Lists global bot administrators.',
  'viewadmins': 'Utility: Displays the admin hierarchy and assigned users.',
  'hierarchy': 'Utility: Shows the role hierarchy and permission tiers.',
  'roles': 'Utility: Lists available bot-related roles.',
  'roleinfo': 'Utility: Provides detailed info about a specific bot role.',
  'myrole': 'Utility: Shows your current permission level and role.',
  'myrank': 'Utility: Displays your rank in the global or server hierarchy.',
  'addbotadmin': 'SuperAdmin: Adds a new global bot administrator.',
  'addglobaladmin': 'SuperAdmin: Alias for adding a global bot administrator.',
  'removebotadmin': 'SuperAdmin: Removes a global bot administrator.',
  'removeglobaladmin': 'SuperAdmin: Alias for removing a global bot administrator.',
  'addserveradmin': 'Admin: Adds an administrator to the current server.',
  'removeserveradmin': 'Admin: Removes an administrator from the current server.',
  'settings': 'Admin: Opens the server settings configuration menu.',
  'serversettings': 'Admin: Displays current server-specific bot settings.',
  'botsettings': 'Admin: Shows global bot configuration (Admins only).',
  'toggle': 'Admin: Quickly toggles specific features on or off.',
  'setpingrole': 'Admin: Sets the role to be pinged for bot updates.',
  'setzoorole': 'Admin: Configures the primary ZooBot member role.',
  'setzooadminrole': 'Admin: Configures the ZooBot administrator role.',
  'setupdateschannel': 'Admin: Sets the channel for bot news and updates.',
  'postupdate': 'SuperAdmin: Broadcasts a bot update to all servers.',
  'botupdate': 'SuperAdmin: Manages bot versioning and updates.',
  'setemoji': 'Admin: Configures custom emojis for bot elements.',
  'setchestgif': 'Admin: Sets a custom GIF for chest opening animations.',
  'setcrategif': 'Admin: Sets a custom GIF for crate opening animations.',
  'delete': 'Admin: Deletes specified bot data.',
  'deleteuser': 'SuperAdmin: Completely wipes a user\'s data from the bot.',
  'joinclan': 'Social: Allows a user to join an existing clan.',
  'leaveclan': 'Social: Allows a user to leave their current clan.',
  'donate': 'Economy: Donate coins or gems to your clan\'s treasury.',
  'clan': 'Social: Shows detailed information about your clan.',
  'clanprofile': 'Social: Displays the profile and stats of a clan.',
  'clans': 'Social: Lists all clans currently active in the system.',
  'clanleaderboard': 'Social: Rankings of the most powerful clans.',
  'start': 'General: Initializes your profile and gives starter rewards.',
  'select': 'General: Selects your primary character for battles/profile.',
  'profile': 'General: Displays your user profile and stats.',
  'addpfp': 'User: Adds a new profile picture to your collection.',
  'pfps': 'User: Lists all your collected profile pictures.',
  'equippfp': 'User: Sets a specific image as your active profile picture.',
  'unequippfp': 'User: Resets your profile picture to the default.',
  'myprofile': 'General: Alias for viewing your own profile.',
  'uploadpfp': 'User: Uploads a custom image for use as a profile picture.',
  'grantpfp': 'Admin: Grants a specific profile picture to a user.',
  'grantpfptoclan': 'Admin: Grants a profile picture for clan-wide use.',
  'listpfps': 'Utility: Lists all available profile pictures in the registry.',
  'trivia': 'Game: Starts a trivia session to earn rewards.',
  'a': 'Game: Shortcut for answering trivia or multi-choice questions.',
  'q': 'Game: Shortcut for asking or viewing QA/trivia content.',
  'qadd': 'Admin: Adds a new question to the trivia database.',
  'qedit': 'Admin: Modifies an existing trivia question.',
  'qdel': 'Admin: Deletes a question from the trivia database.',
  'submitqa': 'User: Submits a custom question for bot approval.',
  'pendingqa': 'Admin: Lists trivia questions awaiting approval.',
  'approveqa': 'Admin: Approves a user-submitted trivia question.',
  'rejectqa': 'Admin: Rejects a user-submitted trivia question.',
  'crate': 'Economy: View details or buy available loot crates.',
  'pickcrate': 'Economy: Choose a specific crate from a drop event.',
  'pickchest': 'Economy: Alias for picking a crate/chest.',
  'opencrate': 'Economy: Opens a crate to reveal characters or items.',
  'openchest': 'Economy: Alias for opening a crate.',
  'bulkopen': 'Economy: Opens multiple crates in a single action.',
  'openall': 'Economy: Opens all crates currently in your inventory.',
  'bulkopencrate': 'Economy: Specifically handles bulk crate opening.',
  'levelup': 'Character: Levels up your active character.',
  'char': 'Character: Displays stats for a specific character.',
  'character': 'Character: Alias for viewing character info.',
  'release': 'Character: Releases a character to gain tokens.',
  'leave': 'Character: Alias for releasing a character.',
  'forcerelease': 'Admin: Forcefully removes a character from a collection.',
  'setdrop': 'Admin: Configures settings for character drop events.',
  'startdrops': 'Admin: Manually triggers a character drop event.',
  'stopdrops': 'Admin: Halts active character drop events.',
  'paydrops': 'Economy: Use currency to trigger an immediate drop.',
  'activatedrops': 'Admin: Enables automated drop events in a channel.',
  'dropstatus': 'Utility: Shows time remaining and status of drops.',
  'revive': 'Economy: Pay to revive a missed or expired drop.',
  'revivedrops': 'Economy: Alias for reviving drop events.',
  'c': 'Shortcut: Common shortcut for character or collection commands.',
  't': 'Shortcut: Common shortcut for trading commands.',
  'trade': 'Economy: Initiates a secure trade with another player.',
  'grant': 'Admin: Grants currency or items to a specific user.',
  'grantust': 'Admin: Grants Universal Skin Tokens to a user.',
  'removeust': 'Admin: Removes Universal Skin Tokens from a user.',
  'ust': 'Economy: Shows your current UST balance and history.',
  'ustbalance': 'Economy: Alias for checking UST balance.',
  'setustrate': 'Admin: Configures the conversion rate for UST.',
  'ustrates': 'Utility: Displays current UST conversion rates.',
  'viewustrates': 'Utility: Alias for viewing UST rates.',
  'grantchar': 'Admin: Directly grants a character to a user.',
  'grantkeys': 'Admin: Grants character-specific keys to a user.',
  'grantkey': 'Admin: Alias for granting keys.',
  'addskin': 'Admin: Adds a new skin to the character skin system.',
  'updateskin': 'Admin: Modifies an existing character skin.',
  'grantskin': 'Admin: Gives a specific skin to a user.',
  'revokeskin': 'Admin: Removes a skin from a user\'s collection.',
  'deleteskin': 'Admin: Permanently deletes a skin from the system.',
  'uploadskin': 'Admin: Uploads image assets for a new skin.',
  'setworkimage': 'Admin: Sets the image displayed during work tasks.'
};

module.exports = { commandDocumentationPart1 };